[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "logdock"
version = "0.1.0"
description = "Biblioteca de logging estruturado com notificações e persistência configurável."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "azure-storage-blob>=12.19.0",
    "tzdata>=2024.1",
]

[project.scripts]
logdock = "logdock.cli:main"

[tool.setuptools]
package-dir = {"" = ".."}

[tool.setuptools.packages.find]
where = [".."]
include = ["logdock*"]
namespaces = true
