import logging

SUPORTED_LEVELS = {
    "INFO": logging.INFO,
    "DEBUG": logging.DEBUG,
    "WARNING": logging.WARNING,
    "ERROR": logging.ERROR
}

SUPORTED_NOTIFICATION_PROVIDERS = ["TELEGRAM", "AZURE_FUNCTION"]

SUPORTED_PERSISTENCE_PROVIDERS = ["AZURE_BLOB_STORAGE"]